name: Build & Deploy – Firebase Functions

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production

    steps:
      # 1.  Checkout repo
      - uses: actions/checkout@v4

      # 2.  PNPM setup + cache
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - name: Restore pnpm cache
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-

      # 3.  Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      # 4.  Install deps & build
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build --if-present

      # 5.  Deploy Functions
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'          # to comment on PRs
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: '${{ secrets.PROJECT_ID }}'
          target: functions
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

